name: repo_test_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  cupertino_icons: ^1.0.8
  connectivity_plus: ^6.1.4
  app_lifecycle_observer:
    git:
      url: git@github.com:marrbor/dart_libs_private.git
      path: app_lifecycle_observer
  connectivity_observer:
    git:
      url: git@github.com:marrbor/dart_libs_private.git
      path: connectivity_observer

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  flutter_lints: ^5.0.0
  custom_lint: ^0.7.5

flutter:
  uses-material-design: true
